spring:
  application:
    name: modistry-backend

  threads:
    virtual:
      enabled: true

  docker:
    compose:
      file: backend/infrastructure/compose.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
server:
  port: 8080

logging:
  level:
    org.springframework.security: trace