spring:
  application:
    name: modistry-gateway
  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          modistry:
            client-id: modistry-gateway
            client-secret: ${MODISTRY_GATEWAY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
        provider:
          modistry:
            issuer-uri: http://localhost:9000
server:
  port: 8081

logging:
  level:
    org.springframework.security: trace
