
spring:
  application:
    name: security-service
  docker:
    compose:
      file: backend/infrastructure/compose.yaml

  security:
    oauth2:
      client:
        registration:
          hytale:
            client-id: ${HYTALE_CLIENT_ID}
            client-secret: ${HYTALE_SECRET}
            scope:
              - openid
              - hytale:profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          hytale:
            issuer-uri: https://connect.accounts.hytale.com

logging:
  level:
    org.springframework.security: trace
server:
  port: 9000

modistry:
  security:
    signing-key:
      location: ${MODISTRY_SIGNING_KEYSTORE}
      password: ${MODISTRY_SIGNING_KEYSTORE_PASSWORD}
      alias: ${MODISTRY_SIGNING_KEY_ALIAS}
